[bindings.kotlin]
package_name = "org.lightningdevkit.ldknode"
cdylib_name = "ldk_node"

[bindings.python]
cdylib_name = "ldk_node"

[bindings.swift]
module_name = "LDKNode"
ffi_module_name = "LDKNodeFFI"
ffi_module_filename ="LDKNodeFFI"
cdylib_name = "ldk_node"
